version: '3'
services:
  # mlworkspace is a all-in-one web-based IDE 
  # see also https://github.com/ml-tooling/ml-workspace
  mlworkspace:
    image: "mltooling/ml-workspace-gpu:0.9.0-SNAPSHOT"
    container_name: "ide"
    ports:
      - "$ideport:8080"
    volumes: 
      - "$workspace:/workspace"
  # A base image for further specialized configurations
  robot:
    image: "sldai/development-base"
    container_name: "robot"
    ports: 
      - "$developmentport:8888"
    volumes: 
      - $workspace:/workspace

  

